//! Adapters for borrowed inputs and associated-type facades.
//!
//! `#[mock]` stores owned argument tuples (`&str` → [`String`], `&[T]` → [`Vec`])
//! via [`ToOwned`]. When the macro cannot expand (generic methods, associated
//! types, borrowed returns), build a manual [`Mock`] and adapt at the call site
//! with these helpers or [`ExpectationBuilder::map_args`](super::ExpectationBuilder::map_args).
//!
//! ## Associated types
//!
//! Associated types are not generated by `#[mock]`. Treat them as a manual
//! adapter: pick concrete owned stand-ins for `Self::Item`, configure
//! `Mock<OwnedArgs, OwnedRet>`, and map at the trait impl boundary.
//!
//! ```rust
//! use airbug::Mock;
//! use airbug::mock::borrowed;
//!
//! trait Store {
//!     type Key;
//!     fn get(&self, key: &Self::Key) -> Option<u64>;
//! }
//!
//! struct Manual {
//!     get: Mock<String, Option<u64>>,
//! }
//!
//! impl Store for Manual {
//!     type Key = String;
//!     fn get(&self, key: &Self::Key) -> Option<u64> {
//!         borrowed::call_to_owned(&self.get, key.as_str())
//!     }
//! }
//! ```

use super::Mock;
use std::{borrow::ToOwned, fmt};

/// Clone a borrowed value into the owned form a [`Mock`] stores (same as `#[mock]`).
pub fn to_owned_arg<B: ToOwned + ?Sized>(borrowed: &B) -> B::Owned {
    borrowed.to_owned()
}

/// Call `mock` after [`ToOwned`] on a borrowed input (for example `&str` → [`String`]).
pub fn call_to_owned<B, R>(mock: &Mock<B::Owned, R>, borrowed: &B) -> R
where
    B: ToOwned + ?Sized,
    B::Owned: fmt::Debug + 'static,
    R: 'static,
{
    mock.call(borrowed.to_owned())
}

/// Fallible variant of [`call_to_owned`].
pub fn try_call_to_owned<B, R>(
    mock: &Mock<B::Owned, R>,
    borrowed: &B,
) -> Result<R, super::MockError>
where
    B: ToOwned + ?Sized,
    B::Owned: fmt::Debug + 'static,
    R: 'static,
{
    mock.try_call(borrowed.to_owned())
}

/// Escape hatch: map call-site args into the mock's owned `A`, then call.
///
/// Prefer this (or [`ExpectationBuilder::map_args`](super::ExpectationBuilder::map_args))
/// when adapting generic or associated-type methods that `#[mock]` cannot expand.
pub fn map_args<A, B, R>(mock: &Mock<A, R>, args: B, map: impl FnOnce(B) -> A) -> R
where
    A: fmt::Debug + 'static,
    R: 'static,
{
    mock.call(map(args))
}
