//! Chart playground: every `viz` diagram drawn once from synthetic data, on one page.
//!
//! The point is to look at the real renderer, not a mockup: the page is assembled by
//! [`report::html`], so it carries the report's own stylesheet and [`viz::REVEAL_CSS`], and
//! every figure is a string returned by the same functions a report calls. Each figure prints
//! its measured markup size, because that is what a report page pays for.
//!
//! ```sh
//! cargo run -p airbug-bench --example viz_gallery
//! open target/viz-playground.html
//! ```
use airbug_bench::{analysis::Decision, report, viz};

/// One rendered figure plus what it costs and what to look at.
struct Demo {
    /// Renderer call and arguments, as a reader would type them.
    source: &'static str,
    html: String,
    /// Why the figure is here: the invariant or edge case it holds.
    shows: &'static str,
}

/// Figures that belong under one heading.
struct Section {
    title: &'static str,
    demos: Vec<Demo>,
}

fn section(title: &'static str, demos: Vec<Demo>) -> Section {
    Section { title, demos }
}

fn main() -> airbug_bench::Result<()> {
    let path = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "target/viz-playground.html".into());
    let sections = [
        scatter_section(),
        effect_section(),
        distribution_section(),
        heat_section(),
        diagram_section(),
        edge_section(),
    ];
    let demos: Vec<&Demo> = sections.iter().flat_map(|s| &s.demos).collect();
    let total: usize = demos.iter().map(|d| d.html.len()).sum();

    let mut content = header(total, &demos);
    content.push_str(&controls());
    for (n, s) in sections.iter().enumerate() {
        content.push_str(&format!(
            "<section class=\"pg-group\"><h2>{} — {} ({} figures)</h2>",
            n + 1,
            s.title,
            s.demos.len()
        ));
        for d in &s.demos {
            content.push_str(&render(d));
        }
        content.push_str("</section>");
    }
    let page = report::html("")
        .replace("<!--DETAILS-->", "")
        .replace("<!--CHARTS-->", &content);
    if let Some(parent) = std::path::Path::new(&path).parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, &page)?;
    println!("figures: {}", demos.len());
    println!("chart markup: {total} bytes");
    println!("reveal css: {} bytes", viz::REVEAL_CSS.len());
    println!("page: {} bytes -> {path}", page.len());
    Ok(())
}

/// One demo as markup, with its measured size.
fn render(d: &Demo) -> String {
    let source = report::html_fragment(&format!("`{}`", d.source))
        .replace("<p>", "")
        .replace("</p>", "");
    format!(
        "<article class=\"pg\"><div class=\"pg-meta\"><code>{source}</code><strong>{} B</strong><span>{}</span></div>{}</article>",
        d.html.len(),
        d.shows,
        d.html,
    )
}

fn header(total: usize, demos: &[&Demo]) -> String {
    let widest = demos
        .iter()
        .map(|d| (d.source, d.html.len()))
        .max_by_key(|(_, len)| *len)
        .unwrap_or(("", 0));
    format!(
        "<section class=\"pg pg-summary\"><h2>Costs</h2>\
         <p>{count} figures drawn by <code>airbug_bench::viz</code>, {total} bytes of markup in \
         total, {} bytes per figure on average. The largest is <code>{widest_source}</code> at \
         {widest_len} B. Motion costs the page one stylesheet of {css} bytes plus roughly \
         {per} bytes per reveal group — the marks themselves are identical to a static render.</p>\
         <p>Every label goes through <code>viz::esc</code> and coordinates are fixed-point, so the \
         figures below are the same strings a report embeds. Nothing on this page is a mockup: each \
         block is generated by the function named above it. Two motions are in use: lines and \
         bars draw themselves along their own length, everything else is a staggered fade. Reload \
         to replay a build; print to get the final frame.</p></section>",
        total / demos.len().max(1),
        count = demos.len(),
        widest_source = widest.0,
        widest_len = widest.1,
        css = viz::REVEAL_CSS.len(),
        per = "<g class=\"rv\" style=\"--s:60ms\">".len(),
    )
}

/// Motion controls. Pure CSS over the classes the figures already carry: the renderer never
/// learns that a playground exists.
fn controls() -> String {
    format!(
        "<nav class=\"pg-controls\"><span>reveal</span>\
         <label><input type=\"checkbox\" id=\"still\"> final frame (as print / reduced-motion)</label>\
         <label><input type=\"checkbox\" id=\"pause\"> pause</label>\
         <label><input type=\"checkbox\" id=\"slow\"> slow ×3</label>\
         <label><input type=\"checkbox\" id=\"flat\"> no stagger</label>\
         <label><input type=\"checkbox\" id=\"nodraw\"> fade instead of draw</label>\
         <label><input type=\"checkbox\" id=\"notes\"> hide caveats</label>\
         <a href=\".\">replay</a></nav><style>{CSS}</style>"
    )
}

const CSS: &str = "
.pg-controls{position:sticky;top:0;z-index:2;background:#fff;border:1px solid var(--border);border-radius:10px;padding:10px 14px;display:flex;gap:14px;flex-wrap:wrap;align-items:center;font-size:13px}
.pg-controls>span{font-weight:700;color:#34574e}
.pg-controls label{display:flex;gap:6px;align-items:center;color:var(--ink)}
.pg{margin:22px 0;padding:0}
.pg-summary p{font-size:13px}
.pg-meta{display:flex;gap:14px;align-items:baseline;flex-wrap:wrap;padding:10px 0 0;border-top:1px solid var(--border)}
.pg-meta code{font-size:12px;background:#e8efed;padding:4px 8px;border-radius:6px;overflow-wrap:anywhere}
.pg-meta strong{font-size:13px;color:var(--accent)}
.pg-meta span{font-size:12px;color:var(--muted);flex:1;min-width:200px}
.pg-group>h2{font-size:16px;letter-spacing:-.2px;margin:38px 0 0;padding-top:14px;border-top:3px solid #dce5e8}
body:has(#still:checked) .rv>g{animation:none;opacity:1;transform:none}
body:has(#still:checked) .rv .dv{animation:none;stroke-dasharray:none;stroke-dashoffset:0}
body:has(#nodraw:checked) .rv .dv{animation:none;stroke-dasharray:none;stroke-dashoffset:0}
body:has(#pause:checked) .rv>g{animation-play-state:paused}
body:has(#slow:checked) .rv>g{animation-duration:960ms}
body:has(#flat:checked) .rv>g{animation-delay:0s}
body:has(#notes:checked) .viz-notes,body:has(#notes:checked) .pg-meta span{display:none}
@media print{.pg-controls{display:none}}
";

fn scatter_section() -> Section {
    let curve: Vec<(f64, f64)> = (0..240)
        .map(|i| {
            let x = i as f64 / 2.4;
            (x, 40. + x * 1.8 + (x / 9.).sin() * 26.)
        })
        .collect();
    let noisy: Vec<(f64, f64)> = curve
        .iter()
        .map(|(x, y)| (*x, y + (x * 7.3).sin() * 34.))
        .collect();
    section(
        "Scatter and dot plots",
        vec![
            Demo {
                source: "charts::dot_plot",
                html: viz::charts::dot_plot(
                    "Wall per observation",
                    &curve,
                    240,
                    "x = observation sequence, y = ns. One point per observation, so a chatty loop shows as a band, not as a wider line.",
                ),
                shows: "one independent unit per dot, thinned only past max_points",
            },
            Demo {
                source: "charts::scatter · two Series",
                html: viz::charts::scatter(
                    "Baseline and candidate on one scale",
                    &[
                        viz::charts::Series::new("baseline", curve.clone()),
                        viz::charts::Series::new("candidate", noisy.clone()),
                    ],
                    120,
                    "Thinned to 120 points per series: the shape stays, individual dots stop meaning one measurement.",
                ),
                shows: "shared scale plus a legend; each series keeps its hue",
            },
            Demo {
                source: "Plot + Domain::Log + figure()",
                html: {
                    let points: Vec<(f64, f64)> = (0..40)
                        .map(|i| {
                            let x = 10f64.powi(i / 4);
                            (x, 12. + f64::from(i) * 3.)
                        })
                        .collect();
                    let mut plot = viz::Plot::new("Throughput against payload size")
                        .size(760., 250.)
                        .x(viz::Domain::Log {
                            min: 1.,
                            max: 100_000.,
                        })
                        .y(viz::Domain::fit(points.iter().map(|p| p.1)))
                        .suffixes(" B", " ops/s")
                        .notes("A linear axis would hide everything below the last decade.");
                    plot.points(&points, viz::Palette::LIGHT.series(0), 3.);
                    plot.path(&points, viz::Palette::LIGHT.neutral, 1.5);
                    plot.figure()
                },
                shows: "orders of magnitude need a log x axis",
            },
        ],
    )
}

fn effect_section() -> Section {
    let rows: Vec<viz::charts::Interval> = (0..9)
        .map(|i| {
            let point = (f64::from(i) - 4.) * 3.4;
            viz::charts::Interval {
                label: format!("case-{i} / wall (ms)"),
                point,
                low: point - 2.2,
                high: point + 4.1,
                decision: verdict(point),
            }
        })
        .collect();
    let bars: Vec<(String, f64, Decision)> = rows
        .iter()
        .map(|r| (r.label.clone(), r.point, r.decision.clone()))
        .collect();
    let cols = vec!["wall (ms)".to_string(), "cpu (ms)".to_string()];
    let heat: Vec<viz::charts::HeatRow> = rows
        .iter()
        .enumerate()
        .map(|(i, r)| viz::charts::HeatRow {
            label: format!("case-{i}"),
            cells: vec![
                Some(r.point),
                if i % 4 == 3 {
                    None
                } else {
                    Some(r.point / 2. + 1.)
                },
            ],
        })
        .collect();
    section(
        "Effects: intervals, bars, signed heat",
        vec![
            Demo {
                source: "charts::forest",
                html: viz::charts::forest(
                    "Effect estimates and confidence intervals",
                    &rows,
                    5.,
                    "Shaded band and dashed lines mark the declared practical margin. Colors follow each metric's declared direction, so red is a regression on either end of the axis.",
                ),
                shows: "the interval, not the point, carries the verdict",
            },
            Demo {
                source: "charts::bars",
                html: viz::charts::bars(
                    "Point estimates by metric",
                    &bars,
                    "%",
                    "The same rows without intervals, kept as its own figure so a reader cannot mistake a bar for a decision.",
                ),
                shows: "point estimates only — deliberately weaker evidence",
            },
            Demo {
                source: "charts::heatmap · Heat::Signed { center: 0. }",
                html: viz::charts::heatmap(
                    "Change by case and metric, in percent",
                    &cols,
                    &heat,
                    viz::charts::Heat::Signed { center: 0. },
                    "%",
                    240,
                    "Ramp centered at zero: the neutral stop is the same color at 0 %, and a blank is a missing measurement, not a zero.",
                ),
                shows: "the same rows as a matrix, neutral at the center",
            },
        ],
    )
}

fn distribution_section() -> Section {
    let lanes = [
        viz::charts::Lane {
            label: "baseline".into(),
            values: (0..14)
                .map(|i| 120. + f64::from((i * 37) % 11) * 4.)
                .collect(),
            median: Some(140.),
            color: Some(viz::Palette::LIGHT.series(0)),
        },
        viz::charts::Lane {
            label: "candidate".into(),
            values: (0..9)
                .map(|i| 132. + f64::from((i * 53) % 17) * 3.)
                .collect(),
            median: Some(156.),
            color: Some(viz::Palette::LIGHT.series(1)),
        },
    ];
    let values: Vec<f64> = (0..60)
        .map(|i| 4. + (f64::from(i) / 6.).sin() * 2. + f64::from(i) * 0.05)
        .collect();
    section(
        "Distributions per independent unit",
        vec![
            Demo {
                source: "charts::strip",
                html: viz::charts::strip(
                    "wall (ms) — independent units",
                    &lanes,
                    "ms",
                    "Lane sizes differ on purpose: unequal units are not rebalanced into a fake pair count.",
                ),
                shows: "one dot per unit, lanes are variants",
            },
            Demo {
                source: "charts::ecdf",
                html: viz::charts::ecdf(
                    "Cumulative share of processes at or below a value",
                    &lanes,
                    "ms",
                    "Where a strip shows which values occurred, this shows how much of each lane sits under a threshold. Lines are drawn in from the left; the share axis is a percentage, so a lane of three units can never reach 100 % by rounding.",
                ),
                shows: "the tail question a strip cannot answer",
            },
            Demo {
                source: "charts::sparkline · Plot::inline",
                html: viz::charts::sparkline("Completed processes", &values, None)
                    + "<p class=\"viz-notes\"><code>Plot::inline</code> stays static on purpose: a \
                       banner that repaints every 1.5 s must not restart a reveal, so the live UI \
                       also omits <code>REVEAL_CSS</code>.</p>",
                shows: "axis-free figure for a status banner, no reveal",
            },
        ],
    )
}

fn heat_section() -> Section {
    let cols: Vec<String> = (1..=12).map(|i| format!("#{i}")).collect();
    let medians: Vec<viz::charts::HeatRow> = ["parse", "load", "render", "shutdown"]
        .iter()
        .map(|name| viz::charts::HeatRow {
            label: format!("{name} / wall (ns) / candidate"),
            cells: cols
                .iter()
                .enumerate()
                .map(|(i, _)| {
                    if (name.len() + i) % 7 == 0 {
                        None
                    } else {
                        let wave = 1. + (f64::from(i as u32) * 0.31).sin().abs();
                        Some(2.0e8 * wave * f64::from(name.len() as u32) * 0.17)
                    }
                })
                .collect(),
        })
        .collect();
    let wide: Vec<viz::charts::HeatRow> = (0..46)
        .map(|r| viz::charts::HeatRow {
            label: format!("case-{r:02} / throughput (MiB/s) / candidate"),
            cells: (0..10)
                .map(|c| Some((f64::from(r) - f64::from(c) * 2.).sin() * 40.))
                .collect(),
        })
        .collect();
    let narrow: Vec<String> = cols.iter().take(10).cloned().collect();
    section(
        "Heat matrices",
        vec![
            Demo {
                source: "charts::heatmap · Heat::RowLocal",
                html: viz::charts::heatmap(
                    "Median per process",
                    &cols,
                    &medians,
                    viz::charts::Heat::RowLocal,
                    "ns",
                    240,
                    "One ramp per row, because these rows are not on the same scale: the darkest cell of a row is its own maximum, not the matrix maximum.",
                ),
                shows: "rows on different scales each own their range",
            },
            Demo {
                source: "charts::heatmap · Heat::Global",
                html: viz::charts::heatmap(
                    "Median per process, one ramp",
                    &cols,
                    &medians,
                    viz::charts::Heat::Global,
                    "ns",
                    240,
                    "One ramp across every cell: here levels are directly comparable, which is exactly what RowLocal gives up.",
                ),
                shows: "comparable cells, one ramp for the whole matrix",
            },
            Demo {
                source: "charts::heatmap · max_cells = 120",
                html: viz::charts::heatmap(
                    "Forty-six cases against ten processes",
                    &narrow,
                    &wide,
                    viz::charts::Heat::RowLocal,
                    "",
                    120,
                    "A budget of 120 cells draws whole rows until it runs out; the rest are counted in the caption, never half-drawn.",
                ),
                shows: "the cap is a sentence, not a clipped matrix",
            },
            Demo {
                source: "report::process_heat",
                html: {
                    let series: Vec<(String, Vec<(u32, f64)>)> = medians
                        .iter()
                        .map(|row| {
                            let points = row
                                .cells
                                .iter()
                                .enumerate()
                                .filter_map(|(c, v)| v.map(|v| (c as u32 + 1, v)))
                                .collect();
                            (row.label.clone(), points)
                        })
                        .collect();
                    report::process_heat(&series)
                        + "<p class=\"viz-notes\">The same call a run page makes, from the same \
                           per-process medians. It returns nothing at all when a series has fewer \
                           than two processes, because one process is not a spread.</p>"
                },
                shows: "the matrix a run page actually embeds",
            },
        ],
    )
}

fn diagram_section() -> Section {
    let lanes: Vec<viz::charts::TimelineLane> = ["baseline", "candidate"]
        .iter()
        .enumerate()
        .map(|(v, name)| viz::charts::TimelineLane {
            label: (*name).into(),
            segments: (0..7)
                .map(|i| viz::charts::Segment {
                    start: f64::from(i) * 3. + f64::from(v as u32) * 1.4,
                    stop: f64::from(i) * 3. + 2.2 + f64::from(v as u32) * 0.6,
                    detail: format!("{} done", i + 1),
                })
                .collect(),
        })
        .collect();
    section(
        "Diagrams and raw primitives",
        vec![
            Demo {
                source: "charts::timeline",
                html: viz::charts::timeline(
                    "Processes by variant",
                    &lanes,
                    "Sampled while the interface is open, so lane edges are approximate: this is a liveness view, not evidence.",
                ),
                shows: "elapsed time per variant, segments are processes",
            },
            Demo {
                source: "Plot primitives: band_y, guide_y, interval, bar, points, legend",
                html: {
                    let mut plot = viz::Plot::new("What the chart builders are made of")
                        .size(760., 210.)
                        .margins(190., 20., 16., 34.)
                        .x(viz::Domain::Linear {
                            min: -30.,
                            max: 30.,
                        })
                        .y(viz::Domain::Categories {
                            labels: vec!["row a".into(), "row b".into(), "row c".into()],
                        })
                        .ticks(5, 0)
                        .suffixes("%", "")
                        .notes("Every chart in the library is this: accumulate marks, then render axes behind them.");
                    plot.band_y(-5., 5.);
                    plot.guide_y(0., Some("0"), viz::Palette::LIGHT.grid);
                    plot.rect(
                        plot.plot_left(),
                        100.,
                        220.,
                        26.,
                        viz::Palette::LIGHT.band,
                        "a rectangle in pixels, not data units",
                    );
                    plot.interval(
                        0.,
                        12.,
                        4.,
                        22.,
                        viz::Palette::LIGHT.bad,
                        "row a",
                        "row a: 12% [4, 22]",
                    );
                    plot.bar(1., -18., viz::Palette::LIGHT.good, "row b", 40.);
                    plot.points(
                        &[(-8., 2.), (2., 2.), (14., 2.)],
                        viz::Palette::LIGHT.unresolved,
                        3.5,
                    );
                    plot.lane_label(2., "row c", 11.);
                    plot.legend(&[
                        ("regression".into(), viz::Palette::LIGHT.bad),
                        ("improvement".into(), viz::Palette::LIGHT.good),
                    ]);
                    plot.figure()
                },
                shows: "one canvas, all six mark kinds",
            },
            Demo {
                source: "Plot::bare + inline",
                html: {
                    let mut plot = viz::Plot::new("Direction of a metric")
                        .size(300., 54.)
                        .margins(8., 8., 6., 6.)
                        .x(viz::Domain::Linear { min: 0., max: 1. })
                        .y(viz::Domain::Linear { min: 0., max: 1. })
                        .bare();
                    if let (Some(l), Some(r), Some(top), Some(bottom)) =
                        (plot.xpx(0.3), plot.xpx(0.7), plot.ypx(0.95), plot.ypx(0.05))
                    {
                        plot.rect(
                            l,
                            top,
                            r - l,
                            bottom - top,
                            viz::Palette::LIGHT.band,
                            "margin",
                        );
                    }
                    plot.path(
                        &[(0.05, 0.8), (0.35, 0.2), (0.65, 0.6), (0.95, 0.15)],
                        viz::Palette::LIGHT.good,
                        2.5,
                    );
                    plot.inline()
                        + "<p class=\"viz-notes\"><code>bare()</code> drops grid, axes and the white \
                           card; <code>inline()</code> renders the finished frame with no reveal.</p>"
                },
                shows: "an unboxed figure that survives inside a paragraph",
            },
        ],
    )
}

fn edge_section() -> Section {
    let hostile = vec![viz::charts::Interval {
        label: "</text><script>alert('case')</script>".into(),
        point: 8.,
        low: 2.,
        high: 15.,
        decision: Decision::Regression,
    }];
    let long_labels = vec![
        viz::charts::Interval {
            label: "a-case-whose-name-keeps-going-and-going / a-metric-called-wall-clock-time-per-operation-in-nanoseconds (ms)".into(),
            point: -12.,
            low: -18.,
            high: -6.,
            decision: Decision::Improvement,
        },
        viz::charts::Interval {
            label: "кейс/метрика со сквозными кириллическими подписями (мс)".into(),
            point: 30.,
            low: 21.,
            high: 41.,
            decision: Decision::Regression,
        },
    ];
    section(
        "Edge cases the renderer must survive",
        vec![
            Demo {
                source: "non-finite input",
                html: viz::charts::dot_plot(
                    "Six points, three of them not numbers",
                    &[
                        (0., 10.),
                        (1., f64::NAN),
                        (2., f64::INFINITY),
                        (3., 14.),
                        (4., f64::NEG_INFINITY),
                        (5., 12.),
                    ],
                    100,
                    "A dropped point is missing data; drawing it at zero would invent a fast measurement.",
                ),
                shows: "NaN and infinity drop out instead of plotting at zero",
            },
            Demo {
                source: "hostile labels and titles",
                html: viz::charts::forest(
                    "<img src=x onerror=alert(1)> titled chart",
                    &hostile,
                    5.,
                    "Titles, labels and tooltips all pass through viz::esc.",
                ),
                shows: "names come from the workload, so they are escaped",
            },
            Demo {
                source: "empty · single zero · one cell",
                html: format!(
                    "{}{}{}",
                    viz::charts::forest(
                        "No intervals at all",
                        &[],
                        5.,
                        "The empty case still renders axes and its own caveat.",
                    ),
                    viz::charts::bars(
                        "Single zero row",
                        &[("zero".into(), 0., Decision::Neutral)],
                        "%",
                        "",
                    ),
                    viz::charts::heatmap(
                        "One case, one metric",
                        &["wall (ms)".to_string()],
                        &[viz::charts::HeatRow {
                            label: "case".into(),
                            cells: vec![Some(0.)],
                        }],
                        viz::charts::Heat::Signed { center: 0. },
                        "%",
                        240,
                        "A matrix this small is a number, and it is drawn as one neutral cell.",
                    ),
                ),
                shows: "no rows, one value, a zero-width interval",
            },
            Demo {
                source: "long and unicode labels",
                html: viz::charts::forest(
                    "Wide and unicode labels",
                    &long_labels,
                    5.,
                    "Truncation is by characters, not bytes, so a Cyrillic label cannot split one.",
                ),
                shows: "labels clip; they never widen the canvas",
            },
        ],
    )
}

fn verdict(point: f64) -> Decision {
    if point > 5. {
        Decision::Regression
    } else if point < -5. {
        Decision::Improvement
    } else if point.abs() > 2.5 {
        Decision::Inconclusive
    } else {
        Decision::WithinMargin
    }
}
